### ISSUE TITLE
Unable to get provider 

### ISSUE THREAD

**Issue by Virtuozoff** [esafirm/android-image-picker#109]
Firsy of all, want to thank you for this lib! It's really cool. But i've got an issue, after uploading apk in market. All phones with api 22 and above work correctly, but 21 and below after launching an app crashes. 
Gradle: implementation('com.github.esafirm.android-image-picker:imagepicker:1.7.5') {
        exclude group: 'com.android.support', module: 'support-compat'
    }
Here is log. Can you suggest something for me? Thank you.
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
02-14 02:35:57.840 7860-7860/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.ua.kindgeek.myapplication, PID: 7860
                                                 java.lang.RuntimeException: Unable to get provider com.esafirm.imagepicker.helper.ImagePickerFileProvider: java.lang.ClassNotFoundException: Didn't find class "com.esafirm.imagepicker.helper.ImagePickerFileProvider" on path: DexPathList[[zip file "/data/app/com.ua.kindgeek.myapplication-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ua.kindgeek.myapplication-1/lib/arm, /vendor/lib, /system/lib]]
                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:5099)
                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4691)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4631)
                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1370)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5356)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.esafirm.imagepicker.helper.ImagePickerFileProvider" on path: DexPathList[[zip file "/data/app/com.ua.kindgeek.myapplication-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ua.kindgeek.myapplication-1/lib/arm, /vendor/lib, /system/lib]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:5084)
                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4691) 
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4631) 
                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1370) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:135) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5356) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703) 
                                                 	Suppressed: java.lang.NoClassDefFoundError: com.esafirm.imagepicker.helper.ImagePickerFileProvider
                                                     at dalvik.system.DexFile.defineClassNative(Native Method)
                                                     at dalvik.system.DexFile.defineClass(DexFile.java:226)
                                                     at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
                                                     at dalvik.system.DexPathList.findClass(DexPathList.java:321)
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
                                                     		... 14 more
                                                 	Suppressed: java.lang.ClassNotFoundException: com.esafirm.imagepicker.helper.ImagePickerFileProvider
                                                     at java.lang.Class.classForName(Native Method)
                                                     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                     		... 13 more

**Comment by esafirm** [comment]
I'm not sure yet, but from a quick look it looks like a multidex or manifest merge issue. 
Have you set the multidex correctly? 

FYI I think you also can make sure if the file is the by using the new APK analyzer.

**Comment by beltranbetania** [comment]
I solved this issue by adding a call to attachBaseContext in the Application class : 

 @Override
  protected void attachBaseContext(Context base) {
    super.attachBaseContext(base);
    MultiDex.install(this);
  }

**Comment by esafirm** [comment]
Well it looks like a multidex issue. Closing this one. Don't hesitate to reopen it
