### ISSUE TITLE
java.lang.IllegalStateException: ReturnMode.GALLERY_ONLY and ReturnMode.ALL is only applicable in Single Mode!

### ISSUE THREAD

**Issue by jinfagang** [esafirm/android-image-picker#112]
this codes lead the error：

```
ImagePicker imagePicker = ImagePicker.create(PostPayFriendActivity.this)
                        .returnMode(ReturnMode.GALLERY_ONLY) // set whether pick action or camera action should return immediate result or not. Only works in single mode for image picker
                        .folderMode(false) // set folder mode (false by default)
                        .toolbarFolderTitle("选择几张美照") // folder selection title
                        .toolbarImageTitle("选择几张美照"); // image selection title

                imagePicker.limit(9) // max images can be selected (99 by default)
                        .showCamera(true) // show camera or not (true by default)
                        .imageDirectory("Camera")   // captured image directory name ("Camera" folder by default)
                        .imageFullDirectory(Environment.getExternalStorageDirectory().getPath()) // can be full path
                        .origin(images) // original selected images, used in multi mode
                        .start(REQUEST_CODE_PICKER); // start image picker activity with request code
            }
```

Did I using wrong params?

the error says:
```
 FATAL EXCEPTION: main
                                                                      Process: com.ouman.luoliluoli, PID: 16985
                                                                      java.lang.IllegalStateException: ReturnMode.GALLERY_ONLY and ReturnMode.ALL is only applicable in Single Mode!
                                                                          at com.esafirm.imagepicker.helper.ConfigUtils.checkConfig(ConfigUtils.java:22)
                                                                          at com.esafirm.imagepicker.features.ImagePicker.getIntent(ImagePicker.java:183)
                                                                          at com.esafirm.imagepicker.features.ImagePicker$ImagePickerWithActivity.start(ImagePicker.java:40)
```

**Comment by esafirm** [comment]
Well the default config for ImagePicker is multiple image picker. The `ReturnMode.GALLERY_ONLY` is only applicable in single mode, because i think it's not making any sense to have it in multiple mode. 

Do you have any specification for your image picker?

**Comment by esafirm** [comment]
Closing this due to inactivity.
