### ISSUE TITLE
Exception thrown when opening again

### ISSUE THREAD

**Issue by romaneso** [esafirm/android-image-picker#147]
While opening up the activity, I get the following error:
```
06-17 14:37:20.618 20553-21804/? E/Parcel: Class not found when unmarshalling: com.esafirm.imagepicker.features.ImagePickerConfig
    java.lang.ClassNotFoundException: com.esafirm.imagepicker.features.ImagePickerConfig
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:324)
        at android.os.Parcel.readParcelableCreator(Parcel.java:2405)
        at android.os.Parcel.readParcelable(Parcel.java:2359)
        at android.os.Parcel.readValue(Parcel.java:2265)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2620)
        at android.os.BaseBundle.unparcel(BaseBundle.java:221)
        at android.os.BaseBundle.getString(BaseBundle.java:920)
        at android.content.Intent.getStringExtra(Intent.java:6221)
        at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2738)
        at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2210)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6626)
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6362)
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:174)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4188)
        at android.os.Binder.execTransact(Binder.java:453)
     Caused by: java.lang.ClassNotFoundException: com.esafirm.imagepicker.features.ImagePickerConfig
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:324) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:2405) 
        at android.os.Parcel.readParcelable(Parcel.java:2359) 
        at android.os.Parcel.readValue(Parcel.java:2265) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2620) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
        at android.os.BaseBundle.getString(BaseBundle.java:920) 
        at android.content.Intent.getStringExtra(Intent.java:6221) 
        at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2738) 
        at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2210) 
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6626) 
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6362) 
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:174) 
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4188) 
        at android.os.Binder.execTransact(Binder.java:453) 
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
06-17 14:37:20.618 29036-29036/? E/Zygote: v2
06-17 14:37:20.878 28943-28943/at.codecrane.chemtrails E/RecyclerView: No adapter attached; skipping layout
06-17 14:37:21.008 28943-28943/at.codecrane.chemtrails E/AndroidRuntime: FATAL EXCEPTION: main
    Process: at.codecrane.chemtrails, PID: 28943
    java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.view.inputmethod.InputConnection.finishComposingText()' on a null object reference
        at android.view.inputmethod.InputConnectionWrapper.finishComposingText(InputConnectionWrapper.java:78)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:362)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:7331)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by esafirm** [comment]
Strange, did you use multidex?

**Comment by daupawar** [comment]
I am getting the same error, and using with multidex

**Comment by esafirm** [comment]
This should not exist anymore because we're using singleton to control the config.

**Comment by esafirm** [comment]
Not reproduced
