### ISSUE TITLE
FATAL EXCEPTION : java.lang.StringIndexOutOfBoundsException: String index out of range: -2

### ISSUE THREAD

**Issue by parvesh-hike** [esafirm/android-image-picker#153]
java.lang.StringIndexOutOfBoundsException: String index out of range: -2
        at java.lang.String.substring(String.java:1975)
        at java.net.DefaultFileNameMap.getContentTypeFor(DefaultFileNameMap.java:38)
        at java.net.URLConnection.guessContentTypeFromName(URLConnection.java:1389)
        at com.esafirm.imagepicker.helper.ImagePickerUtils.isVideoFormat(ImagePickerUtils.java:85)
        at com.esafirm.imagepicker.adapter.ImagePickerAdapter.onBindViewHolder(ImagePickerAdapter.java:66)
        at com.esafirm.imagepicker.adapter.ImagePickerAdapter.onBindViewHolder(ImagePickerAdapter.java:23)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:762)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2656)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2365)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1530)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7316)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:778)
        at android.view.Choreographer.doFrame(Choreographer.java:713)

100% crash when my filepath contains "#".

**Comment by esafirm** [comment]
Is it your image name that have "#" symbol?

**Comment by joshfriend** [comment]
I have a very similar, slightly different crash

```
Fatal Exception: java.lang.StringIndexOutOfBoundsException: String index out of range: -27
       at java.lang.String.substring(String.java:1975)
       at java.net.DefaultFileNameMap.getContentTypeFor(DefaultFileNameMap.java:38)
       at java.net.URLConnection.guessContentTypeFromName(URLConnection.java:1381)
       at com.esafirm.imagepicker.helper.ImagePickerUtils.getNameFromFilePath(Unknown Source:4)
       at com.esafirm.imagepicker.adapter.ImagePickerAdapter.onBindViewHolder(Unknown Source:56)
       at com.esafirm.imagepicker.adapter.ImagePickerAdapter.onBindViewHolder(Unknown Source:2)
       at android.support.v7.widget.RecyclerView$Adapter.onCreateViewHolder(Unknown Source)
```
