### ISSUE TITLE
File not found exception

### ISSUE THREAD

**Issue by ShivamNeetable** [esafirm/android-image-picker#195]

**Comment by ShivamNeetable** [comment]
```
2019-02-13 14:49:18.335 5797-5828/? W/CameraImpl: stopCaptureSession() - Stop capture session for camera '0'
2019-02-13 14:49:18.336 5797-5828/? W/CameraImpl: stopDriverCaptureSession() - Stop repeating
2019-02-13 14:49:18.336 5797-5828/? W/CameraImpl: stopDriverCaptureSession() - Close session
2019-02-13 14:49:18.336 5797-5828/? W/CameraImpl: stopDriverCaptureSession() - Waiting for stop [start]
2019-02-13 14:49:18.338 7504-28959/? E/OnePlusAppBootManager: forbid start cpi=ContentProviderInfo{name=in.merck.live.imagepicker.provider className=com.esafirm.imagepicker.helper.ImagePickerFileProvider}
2019-02-13 14:49:18.338 5797-5905/? E/ActivityThread: Failed to find provider info for in.merck.live.imagepicker.provider
2019-02-13 14:49:18.338 5797-5905/? E/RequestedPhotoSaveTask: onSaveToFile() - Open output stream error
2019-02-13 14:49:18.338 5797-5905/? W/System.err: java.io.FileNotFoundException: No content provider: content://in.merck.live.imagepicker.provider/external_files/Pictures/Pictures/IMG_20190213_1449106118514972700577127.jpg
2019-02-13 14:49:18.338 5797-5905/? W/System.err:     at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1344)
2019-02-13 14:49:18.338 5797-5905/? W/System.err:     at android.content.ContentResolver.openOutputStream(ContentResolver.java:1100)
2019-02-13 14:49:18.338 5797-5905/? W/System.err:     at com.oneplus.camera.io.RequestedPhotoSaveTask.onSaveToFile(RequestedPhotoSaveTask.java:85)
2019-02-13 14:49:18.338 5797-5905/? W/System.err:     at com.oneplus.camera.io.MediaSaveTask.saveMediaToFile(MediaSaveTask.java:502)
2019-02-13 14:49:18.338 5797-5905/? W/System.err:     at com.oneplus.camera.io.FileManagerImpl$FileManageerThread$1.handleMessage(FileManagerImpl.java:478)
2019-02-13 14:49:18.338 5797-5905/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2019-02-13 14:49:18.338 5797-5905/? W/System.err:     at android.os.Looper.loop(Looper.java:193)
2019-02-13 14:49:18.338 5797-5905/? W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by esafirm** [comment]
When this error happen?

**Comment by esafirm** [comment]
Not reproducible
