### ISSUE TITLE
Class not found when unmarshalling

### ISSUE THREAD

**Issue by mahmoudshabat** [esafirm/android-image-picker#208]
in Version below 22 , there some bugs when load multi images 

`E/Parcel: Class not found when unmarshalling: com.esafirm.imagepicker.features.ImagePickerConfig
    java.lang.ClassNotFoundException: com.esafirm.imagepicker.features.ImagePickerConfig
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:324)
        at android.os.Parcel.readParcelableCreator(Parcel.java:2404)
        at android.os.Parcel.readParcelable(Parcel.java:2358)
        at android.os.Parcel.readValue(Parcel.java:2264)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
        at android.os.BaseBundle.unparcel(BaseBundle.java:221)
        at android.os.BaseBundle.getString(BaseBundle.java:920)
        at android.content.Intent.getStringExtra(Intent.java:6221)
        at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2752)
        at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2210)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6655)
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6389)
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:174)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4208)
        at android.os.Binder.execTransact(Binder.java:453)
     Caused by: java.lang.ClassNotFoundException: com.esafirm.imagepicker.features.ImagePickerConfig
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:324) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:2404) 
        at android.os.Parcel.readParcelable(Parcel.java:2358) 
        at android.os.Parcel.readValue(Parcel.java:2264) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2614) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
        at android.os.BaseBundle.getString(BaseBundle.java:920) 
        at android.content.Intent.getStringExtra(Intent.java:6221) 
        at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2752) 
        at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2210) 
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6655) 
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6389) 
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:174) 
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4208) 
        at android.os.Binder.execTransact(Binder.java:453) `
## Specifications

  - Image Picker Version:1.13.0
  - Android OS: below 21
  - Phone:

**Comment by esafirm** [comment]
Have you tried version 2.0.0? 

https://github.com/esafirm/android-image-picker/releases/tag/2.0.0

**Comment by immustafa** [comment]
Hi, I tried with 2.0.0 but getting same error on logcat like  this;

 E/Parcel: Class not found when unmarshalling: com.esafirm.imagepicker.features.ImagePickerConfig
    java.lang.ClassNotFoundException: com.esafirm.imagepicker.features.ImagePickerConfig
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:324)
        at android.os.Parcel.readParcelableCreator(Parcel.java:2404)
        at android.os.Parcel.readParcelable(Parcel.java:2358)
        at android.os.Parcel.readValue(Parcel.java:2264)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
        at android.os.BaseBundle.unparcel(BaseBundle.java:221)
        at android.os.BaseBundle.getString(BaseBundle.java:920)
        at android.content.Intent.getStringExtra(Intent.java:6221)
        at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2752)
        at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2210)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6656)
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6390)
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:174)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4209)
        at android.os.Binder.execTransact(Binder.java:453)
     Caused by: java.lang.ClassNotFoundException: com.esafirm.imagepicker.features.ImagePickerConfig
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:324) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:2404) 
        at android.os.Parcel.readParcelable(Parcel.java:2358) 
        at android.os.Parcel.readValue(Parcel.java:2264) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2614) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
        at android.os.BaseBundle.getString(BaseBundle.java:920) 
        at android.content.Intent.getStringExtra(Intent.java:6221) 
        at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2752) 
        at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2210) 
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6656) 
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6390) 
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:174) 
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4209) 
        at android.os.Binder.execTransact(Binder.java:453) 
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available



but it is working, I cant understand

version : 2.0.0
OS : 23

**Comment by esafirm** [comment]
> but it is working, I cant understand

So this happen but the app didn't crash? 

Are you running things with `minify` enabled?

**Comment by mahmoudshabat** [comment]
> 
> 
> > but it is working, I cant understand
> 
> So this happen but the app didn't crash?
> 
> Are you running things with `minify` enabled?

* yes , happen but no crash 
* `minify`  enabled

**Comment by HiteshDevganiya** [comment]
I am using `implementation 'com.github.esafirm.android-image-picker:imagepicker:2.2.0'` and still facing this issue.

**Comment by ArunkumarAndanshetti** [comment]
I am facing issue in fragment so please rectify it

**Comment by 7alma9** [comment]
facing same issue and in onActivityResult getting less item then selected

**Comment by yanivshaked** [comment]
Any update on this issue? 
When running debug mode (simple `flutter run`), there is no issue. The gallery is opened and I can select an image.
When running release mode (`flutter run --release`), I am getting that error message on logcat. Note it doesn't happen on all devices, but I have seen it on Android S10.

**Comment by tamimattafi** [comment]
Happens also on Android 11 Samsung S21 Ultra.

**Comment by LoveWFan** [comment]
Happens also on Android 11 Samsung Gallery S10
and crash
