### ISSUE TITLE
class not found

### ISSUE THREAD

**Issue by amir14a** [esafirm/android-image-picker#225]
this is logcat:

    java.lang.ClassNotFoundException: com.esafirm.imagepicker.features.ImagePickerConfig
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:308)
        at java.lang.Class.forName(Class.java:272)
        at android.os.Parcel.readParcelableCreator(Parcel.java:2275)
        at android.os.Parcel.readParcelable(Parcel.java:2239)
        at android.os.Parcel.readValue(Parcel.java:2146)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2479)
        at android.os.BaseBundle.unparcel(BaseBundle.java:221)
        at android.os.BaseBundle.getString(BaseBundle.java:918)
        at android.content.Intent.getStringExtra(Intent.java:5386)
        at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1803)
        at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1355)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4637)
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:4480)
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:140)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3019)
        at android.os.Binder.execTransact(Binder.java:446)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.esafirm.imagepicker.features.ImagePickerConfig" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:308) 
        at java.lang.Class.forName(Class.java:272) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:2275) 
        at android.os.Parcel.readParcelable(Parcel.java:2239) 
        at android.os.Parcel.readValue(Parcel.java:2146) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2479) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
        at android.os.BaseBundle.getString(BaseBundle.java:918) 
        at android.content.Intent.getStringExtra(Intent.java:5386) 
        at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1803) 
        at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1355) 
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4637) 
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:4480) 
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:140) 
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3019) 
        at android.os.Binder.execTransact(Binder.java:446) 
    	Suppressed: java.lang.ClassNotFoundException: com.esafirm.imagepicker.features.ImagePickerConfig
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 18 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
06-12 14:02:51.471 2012-2012/? E/auditd: In denial and Property audit_ondenial is set to 1 
06-12 14:02:51.561 5868-5868/amir.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
    Process: amir.myapplication, PID: 5868
    java.lang.StringIndexOutOfBoundsException: length=38; regionStart=35; regionLength=-15
        at java.lang.String.startEndAndLength(String.java:504)
        at java.lang.String.substring(String.java:1333)
        at java.net.DefaultFileNameMap.getContentTypeFor(DefaultFileNameMap.java:38)
        at java.net.URLConnection.guessContentTypeFromName(URLConnection.java:680)
        at com.esafirm.imagepicker.helper.ImagePickerUtils.isVideoFormat(ImagePickerUtils.java:85)
        at com.esafirm.imagepicker.adapter.ImagePickerAdapter.onBindViewHolder(ImagePickerAdapter.java:66)
        at com.esafirm.imagepicker.adapter.ImagePickerAdapter.onBindViewHolder(ImagePickerAdapter.java:23)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6508)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5484)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5750)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
        at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
        at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
        at android.view.View.layout(View.java:16678)
        at android.view.ViewGroup.layout(ViewGroup.java:5328)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
        at android.view.View.layout(View.java:16678)
        at android.view.ViewGroup.layout(ViewGroup.java:5328)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
        at android.view.View.layout(View.java:16678)
        at android.view.ViewGroup.layout(ViewGroup.java:5328)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
        at android.view.View.layout(View.java:16678)
        at android.view.ViewGroup.layout(ViewGroup.java:5328)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
        at android.view.View.layout(View.java:16678)
        at android.view.ViewGroup.layout(ViewGroup.java:5328)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
        at android.view.View.layout(View.java:16678)
        at android.view.ViewGroup.layout(ViewGroup.java:5328)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
        at android.view.View.layout(View.java:16678)
        at android.view.ViewGroup.layout(ViewGroup.java:5328)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2321)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2034)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6644)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
        at android.view.Choreographer.doCallbacks(Choreographer.java:590)
        at android.view.Choreographer.doFrame(Choreographer.java:560)

  - Image Picker Version:1.3.1
  - Android OS:21
  - Phone:Note 3

**Comment by esafirm** [comment]
Have you enabled `MultiDexApplication` in your app?

**Comment by esafirm** [comment]
Closing this due inactivity
