### ISSUE TITLE
I am getting android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by priyankachoprathecoder** [esafirm/android-image-picker#240]
I am getting RuntimeException in the crashlytics

  - Image Picker Version: 2.0.0
  - Android OS: 6.0 to 9.0

Full stack trace:

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.xxxx/com.esafirm.imagepicker.features.ImagePickerActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f080078
       at android.app.ActivityThread.performLaunchActivity + 2956(ActivityThread.java:2956)
       at android.app.ActivityThread.handleLaunchActivity + 3091(ActivityThread.java:3091)
       at android.app.servertransaction.LaunchActivityItem.execute + 78(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks + 108(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute + 68(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage + 1843(ActivityThread.java:1843)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 193(Looper.java:193)
       at android.app.ActivityThread.main + 6758(ActivityThread.java:6758)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 497(RuntimeInit.java:497)
       at com.android.internal.os.ZygoteInit.main + 912(ZygoteInit.java:912)

       Caused by android.content.res.Resources$NotFoundException: Resource ID #0x7f080078
       at android.content.res.ResourcesImpl.getValueForDensity + 230(ResourcesImpl.java:230)
       at android.content.res.Resources.getDrawableForDensity + 887(Resources.java:887)
       at android.content.res.Resources.getDrawable + 827(Resources.java:827)
       at android.content.Context.getDrawable + 631(Context.java:631)
       at androidx.core.content.ContextCompat.c + 6(ContextCompat.java:6)
       at com.esafirm.imagepicker.helper.ViewUtils.getArrowIcon + 4(ViewUtils.java:4)
       at com.esafirm.imagepicker.features.ImagePickerActivity.setupView + 4(ImagePickerActivity.java:4)
       at android.app.Activity.performCreate + 7136(Activity.java:7136)
       at android.app.Activity.performCreate + 7127(Activity.java:7127)
       at android.app.Instrumentation.callActivityOnCreate + 1271(Instrumentation.java:1271)
       at android.app.ActivityThread.performLaunchActivity + 2933(ActivityThread.java:2933)
       at android.app.ActivityThread.handleLaunchActivity + 3091(ActivityThread.java:3091)
       at android.app.servertransaction.LaunchActivityItem.execute + 78(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks + 108(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute + 68(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage + 1843(ActivityThread.java:1843)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 193(Looper.java:193)
       at android.app.ActivityThread.main + 6758(ActivityThread.java:6758)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 497(RuntimeInit.java:497)
       at com.android.internal.os.ZygoteInit.main + 912(ZygoteInit.java:912)

**Comment by esafirm** [comment]
Please reopen if this is happening in 3.x

**Comment by jerinamathews** [comment]
Its happening in 3.x version. Am getting this error

> Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.<package>/com.esafirm.imagepicker.features.ImagePickerActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f08006c
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3502)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3683)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7977)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:948)


> Caused by android.content.res.Resources$NotFoundException: Resource ID #0x7f08006c
       at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:246)
       at android.content.res.Resources.getDrawableForDensity(Resources.java:982)
       at android.content.res.Resources.getDrawable(Resources.java:922)
       at android.content.Context.getDrawable(Context.java:694)
       at androidx.core.content.ContextCompat$Api21Impl.getDrawable(ContextCompat.java:864)
       at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:483)
       at com.esafirm.imagepicker.helper.ViewUtils.getArrowIcon(ViewUtils.java:19)
       at com.esafirm.imagepicker.features.ImagePickerActivity.setupView(ImagePickerActivity.java:133)
       at com.esafirm.imagepicker.features.ImagePickerActivity.onCreate(ImagePickerActivity.java:62)
       at android.app.Activity.performCreate(Activity.java:8125)
       at android.app.Activity.performCreate(Activity.java:8108)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3472)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3683)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7977)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:948)

**Comment by jerinamathews** [comment]
@priyankachoprathecoder did you solved this?
