### ISSUE TITLE
Class Not Found Exception

### ISSUE THREAD

**Issue by codingblazer** [esafirm/android-image-picker#26]
@esafirm Hey , I am encountering following exception when click the "Pick Photo" button (which starts the intent)
```

Process: com.example.sachinaggarwal.tripadvisor, PID: 1721
                                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.sachinaggarwal.tripadvisor/com.esafirm.imagepicker.features.ImagePickerActivity}: android.view.InflateException: Binary XML file line #33: Binary XML file line #33: Error inflating class android.support.v7.widget.RecyclerView
                                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
                                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                                       Caused by: android.view.InflateException: Binary XML file line #33: Binary XML file line #33: Error inflating class android.support.v7.widget.RecyclerView
                                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                                          at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
                                                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
                                                                                          at com.esafirm.imagepicker.features.ImagePickerActivity.onCreate(ImagePickerActivity.java:88)
                                                                                          at android.app.Activity.performCreate(Activity.java:6245)
                                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
                                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                                                       Caused by: android.view.InflateException: Binary XML file line #33: Error inflating class android.support.v7.widget.RecyclerView
                                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
                                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                          at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288) 
                                                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143) 
                                                                                          at com.esafirm.imagepicker.features.ImagePickerActivity.onCreate(ImagePickerActivity.java:88) 
                                                                                          at android.app.Activity.performCreate(Activity.java:6245) 
                                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130) 
                                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379) 
                                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                                                       Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.RecyclerView" on path: DexPathList[[zip file "/data/app/com.example.sachinaggarwal.tripadvisor-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.sachinaggarwal.tripadvisor-2/lib/arm64, /vendor/lib64, /system/lib64]]
                                                                                          at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:583)
                                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                          at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288) 
                                                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143) 
                                                                                          at com.esafirm.imagepicker.features.ImagePickerActivity.onCreate(ImagePickerActivity.java:88) 
                                                                                          at android.app.Activity.performCreate(Activity.java:6245) 
                                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130) 
                                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379) 
                                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                                                      	Suppressed: java.lang.ClassNotFoundException: android.support.v7.widget.RecyclerView
                                                                                          at java.lang.Class.classForName(Native Method)
                                                                                          at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                          at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                          		... 24 more
                                                                                       Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by esafirm** [comment]
Have you tried adding `@aar` at the end of Gradle dependency declaration? (readme updated to this)

**Comment by esafirm** [comment]
@codingblazer if you're still having this issue please add the `recyclerview` to your `build.gradle` and use the `@aar` format. Thanks
