### ISSUE TITLE
2.3.1 Version not working when app is in release mode

### ISSUE THREAD

**Issue by covocisdev** [esafirm/android-image-picker#276]
W/Glide: Load failed for /storage/emulated/0/WhatsApp/Media/WhatsApp Images/IMG-20200528-WA0006.jpg with size [512x512]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There were 3 causes:
    java.io.FileNotFoundException(/storage/emulated/0/WhatsApp/Media/WhatsApp Images/IMG-20200528-WA0006.jpg: open failed: EACCES (Permission denied))
    java.io.FileNotFoundException(open failed: EACCES (Permission denied))
    java.io.FileNotFoundException(open failed: EACCES (Permission denied))
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, LOCAL
    There was 1 cause:
    java.io.FileNotFoundException(/storage/emulated/0/WhatsApp/Media/WhatsApp Images/IMG-20200528-WA0006.jpg: open failed: EACCES (Permission denied))
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 cause:
    java.io.FileNotFoundException(/storage/emulated/0/WhatsApp/Media/WhatsApp Images/IMG-20200528-WA0006.jpg: open failed: EACCES (Permission denied))
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.io.FileNotFoundException: /storage/emulated/0/WhatsApp/Media/WhatsApp Images/IMG-20200528-WA0006.jpg: open failed: EACCES (Permission denied)
      Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class android.os.ParcelFileDescriptor, LOCAL
    There was 1 cause:
    java.io.FileNotFoundException(open failed: EACCES (Permission denied))
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 cause:
    java.io.FileNotFoundException(open failed: EACCES (Permission denied))
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.io.FileNotFoundException: open failed: EACCES (Permission denied)
      Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class android.content.res.AssetFileDescriptor, LOCAL
    There was 1 cause:
    java.io.FileNotFoundException(open failed: EACCES (Permission denied))
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class java.io.FileNotFoundException: open failed: EACCES (Permission denied)
I/Glide: Root cause (1 of 3)
    java.io.FileNotFoundException: /storage/emulated/0/WhatsApp/Media/WhatsApp Images/IMG-20200528-WA0006.jpg: open failed: EACCES (Permission denied)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileInputStream.<init>(FileInputStream.java:159)
        at java.io.FileInputStream.<init>(FileInputStream.java:115)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:1187)
        at com.bumptech.glide.load.data.o.b(StreamLocalUriFetcher.java:74)
        at com.bumptech.glide.load.data.o.a(StreamLocalUriFetcher.java:50)
        at com.bumptech.glide.load.data.o.a(StreamLocalUriFetcher.java:13)
        at com.bumptech.glide.load.data.l.a(LocalUriFetcher.java:44)
        at com.bumptech.glide.load.model.q$a.a(MultiModelLoader.java:100)
        at com.bumptech.glide.load.engine.w.b(SourceGenerator.java:70)
        at com.bumptech.glide.load.engine.w.b(SourceGenerator.java:63)
        at com.bumptech.glide.load.engine.DecodeJob.l(DecodeJob.java:310)
        at com.bumptech.glide.load.engine.DecodeJob.n(DecodeJob.java:279)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
        at com.bumptech.glide.load.engine.executor.a$b$a.run(GlideExecutor.java:393)
     Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
        at libcore.io.IoBridge.open(IoBridge.java:482)
        at java.io.FileInputStream.<init>(FileInputStream.java:159) 
        at java.io.FileInputStream.<init>(FileInputStream.java:115) 
        at android.content.ContentResolver.openInputStream(ContentResolver.java:1187) 
        at com.bumptech.glide.load.data.o.b(StreamLocalUriFetcher.java:74) 
        at com.bumptech.glide.load.data.o.a(StreamLocalUriFetcher.java:50) 
        at com.bumptech.glide.load.data.o.a(StreamLocalUriFetcher.java:13) 
        at com.bumptech.glide.load.data.l.a(LocalUriFetcher.java:44) 
        at com.bumptech.glide.load.model.q$a.a(MultiModelLoader.java:100) 
        at com.bumptech.glide.load.engine.w.b(SourceGenerator.java:70) 
        at com.bumptech.glide.load.engine.w.b(SourceGenerator.java:63) 
        at com.bumptech.glide.load.engine.DecodeJob.l(DecodeJob.java:310) 
        at com.bumptech.glide.load.engine.DecodeJob.n(DecodeJob.java:279) 
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
        at com.bumptech.glide.load.engine.executor.a$b$a.run(GlideExecutor.java:393) 
    Root cause (2 of 3)
    java.io.FileNotFoundException: open failed: EACCES (Permission denied)
        at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:319)
        at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:224)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1500)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1422)
        at com.bumptech.glide.load.data.i.a(FileDescriptorLocalUriFetcher.java:20)
        at com.bumptech.glide.load.data.i.a(FileDescriptorLocalUriFetcher.java:12)
        at com.bumptech.glide.load.data.l.a(LocalUriFetcher.java:44)
        at com.bumptech.glide.load.model.q$a.a(MultiModelLoader.java:100)
        at com.bumptech.glide.load.engine.w.b(SourceGenerator.java:70)
        at com.bumptech.glide.load.engine.w.b(SourceGenerator.java:63)
        at com.bumptech.glide.load.engine.DecodeJob.l(DecodeJob.java:310)
        at com.bumptech.glide.load.engine.DecodeJob.a(DecodeJob.java:408)
        at com.bumptech.glide.load.engine.w.a(SourceGenerator.java:160)
        at com.bumptech.glide.load.engine.w$a.a(SourceGenerator.java:83)
        at com.bumptech.glide.load.model.q$a.d(MultiModelLoader.java:167)
        at com.bumptech.glide.load.model.q$a.a(MultiModelLoader.java:154)
        at com.bumptech.glide.load.data.l.a(LocalUriFetcher.java:49)
        at com.bumptech.glide.load.model.q$a.a(MultiModelLoader.java:100)
        at com.bumptech.glide.load.engine.w.b(SourceGenerator.java:70)
        at com.bumptech.glide.load.engine.w.b(SourceGenerator.java:63)
        at com.bumptech.glide.load.engine.DecodeJob.l(DecodeJob.java:310)
        at com.bumptech.glide.load.engine.DecodeJob.n(DecodeJob.java:279)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
        at com.bumptech.glide.load.engine.executor.a$b$a.run(GlideExecutor.java:393)
I/Glide: Root cause (3 of 3)
    java.io.FileNotFoundException: open failed: EACCES (Permission denied)
        at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:319)
        at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:224)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1500)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1422)
        at com.bumptech.glide.load.data.a.a(AssetFileDescriptorLocalUriFetcher.java:20)
        at com.bumptech.glide.load.data.a.a(AssetFileDescriptorLocalUriFetcher.java:11)
        at com.bumptech.glide.load.data.l.a(LocalUriFetcher.java:44)
        at com.bumptech.glide.load.engine.w.b(SourceGenerator.java:70)
        at com.bumptech.glide.load.engine.w.b(SourceGenerator.java:63)
        at com.bumptech.glide.load.engine.DecodeJob.l(DecodeJob.java:310)
        at com.bumptech.glide.load.engine.DecodeJob.a(DecodeJob.java:408)
        at com.bumptech.glide.load.engine.w.a(SourceGenerator.java:160)
        at com.bumptech.glide.load.engine.w$a.a(SourceGenerator.java:83)
        at com.bumptech.glide.load.model.q$a.d(MultiModelLoader.java:167)
        at com.bumptech.glide.load.model.q$a.a(MultiModelLoader.java:154)
        at com.bumptech.glide.load.data.l.a(LocalUriFetcher.java:49)
        at com.bumptech.glide.load.model.q$a.a(MultiModelLoader.java:100)
        at com.bumptech.glide.load.engine.w.b(SourceGenerator.java:70)
        at com.bumptech.glide.load.engine.w.b(SourceGenerator.java:63)
        at com.bumptech.glide.load.engine.DecodeJob.l(DecodeJob.java:310)
        at com.bumptech.glide.load.engine.DecodeJob.a(DecodeJob.java:408)
        at com.bumptech.glide.load.engine.w.a(SourceGenerator.java:160)
        at com.bumptech.glide.load.engine.w$a.a(SourceGenerator.java:83)
        at com.bumptech.glide.load.model.q$a.d(MultiModelLoader.java:167)
        at com.bumptech.glide.load.model.q$a.a(MultiModelLoader.java:154)
        at com.bumptech.glide.load.data.l.a(LocalUriFetcher.java:49)
        at com.bumptech.glide.load.model.q$a.a(MultiModelLoader.java:100)
        at com.bumptech.glide.load.engine.w.b(SourceGenerator.java:70)
        at com.bumptech.glide.load.engine.w.b(SourceGenerator.java:63)
        at com.bumptech.glide.load.engine.DecodeJob.l(DecodeJob.java:310)
        at com.bumptech.glide.load.engine.DecodeJob.n(DecodeJob.java:279)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
        at com.bumptech.glide.load.engine.executor.a$b$a.run(GlideExecutor.java:393)

## Steps to Reproduce the Problem

  1. run in release build
  2. try to load image in glide using image.getPath()

## Specifications

  - Image Picker Version: 2.3.1
  - Android OS: 10
  - Phone: Nokia 6.1

**Comment by blegoh** [comment]
i have the same problem even though in debug mode, just in android 10

**Comment by Abhishek95872** [comment]
This is a Glide issue for android 10 and fixed in Glide 4.10.0. kindly update the glide library for this image picker to 4.10.0.

**Comment by blegoh** [comment]
i already use glide:4.11.0, but still get this error

**Comment by IbrahimMAATKI** [comment]
If you target Android 10 or higher(targetSdkVersion >= 29), set the value of requestLegacyExternalStorage to true in your app's manifest file:

<manifest ... >
    
    <application android:requestLegacyExternalStorage="true" ... >
      ...
    </application>
</manifest>

**Comment by ShehryarAhmed** [comment]
> If you target Android 10 or higher(targetSdkVersion >= 29), set the value of requestLegacyExternalStorage to true in your app's manifest file:
> 
> ```
> <manifest ... >
>     
>     <application android:requestLegacyExternalStorage="true" ... >
>       ...
>     </application>
> </manifest>
> ```

getting an error when publishing on google play store

**Comment by abkoradiya** [comment]
I am facing this In android 9 also.

**Comment by esafirm** [comment]
@covocisdev @abkoradiya so the problem exist when you want to load a path that returned by Android image picker?

**Comment by abkoradiya** [comment]
> @covocisdev @abkoradiya so the problem exist when you want to load a path that returned by Android image picker?

@esafirm I think it looks like issue of media database.
I have added one temp condition for file existence for skipping that images.
`if (!new File(path).exists()) {
                        Log.e("FileLoader", "run: file noe exist skipped");
                        continue;
                    }`

**Comment by esafirm** [comment]
@abkoradiya it can be due to [scoped storage](https://developer.android.com/training/data-storage#scoped-storage) in Android 10

The internal image loader have to adapt to this change as well you check in [here](https://github.com/esafirm/android-image-picker/blob/master/imagepicker/src/main/java/com/esafirm/imagepicker/features/imageloader/DefaultImageLoader.java#L18) 

As for convenience `Image` now have `getUri` method https://github.com/esafirm/android-image-picker/pull/285
