### ISSUE TITLE
Crash : SecurityException: Permission Denial

### ISSUE THREAD

**Issue by SabrewingInfotech** [esafirm/android-image-picker#288]
Got crash in **2.2.0** : 
Fatal Exception: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/file from pid=16233, uid=15178 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()

`Fatal Exception: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/file from pid=16233, uid=15178 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
       at android.os.Parcel.readException(Parcel.java:1967)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
       at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
       at android.content.ContentResolver.query(ContentResolver.java:760)
       at android.content.ContentResolver.query(ContentResolver.java:710)
       at android.content.ContentResolver.query(ContentResolver.java:668)
       at com.esafirm.imagepicker.features.fileloader.DefaultImageFileLoader$ImageLoadRunnable.run(DefaultImageFileLoader.java:113)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)`

![Annotation 2020-09-07 151732](https://user-images.githubusercontent.com/10861597/92374438-56c02500-f11d-11ea-8bd7-1905b35bc6f6.png)

**Comment by caitouYang** [comment]
How did you solve the problem

**Comment by Kanunnikoff** [comment]
Got the same issue on v2.4.1...

**Comment by esafirm** [comment]
Hmm 2.4.5 should fix this actually. If not can you check `3.0.0`?
