### ISSUE TITLE
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bumptech/glide/Glide;

### ISSUE THREAD

**Issue by tomtharakan** [esafirm/android-image-picker#30]
Process: driver.codepoints.com.driver, PID: 26988
                                                                              java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bumptech/glide/Glide;
                                                                                  at com.esafirm.imagepicker.adapter.ImagePickerAdapter.onBindViewHolder(ImagePickerAdapter.java:47)
                                                                                  at com.esafirm.imagepicker.adapter.ImagePickerAdapter.onBindViewHolder(ImagePickerAdapter.java:20)

**Comment by teknorix-dev** [comment]
Use dependancy of Glide
compile 'com.github.bumptech.glide:glide:3.7.0'
more info [here](https://github.com/bumptech/glide)

**Comment by esafirm** [comment]
What @teknorix-dev said. Document updated. Sorry 😞
