### ISSUE TITLE
NullPointerException at DefaultImageFileLoader

### ISSUE THREAD

**Issue by dimmells** [esafirm/android-image-picker#311]
App crashes at DefaultImageFileLoader.
 `Fatal Exception: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter name
       at com.esafirm.imagepicker.model.Image.<init>(:2)
       at com.esafirm.imagepicker.features.fileloader.DefaultImageFileLoader$ImageLoadRunnable.run(DefaultImageFileLoader.java:159)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)`

I tried to use custom ImageFileLoader in which i fixed this issue, but it doesnt used by lib.
I call this every time before creating ImagePicker. Maybe I do something wrong?
` ImagePickerComponentHolder.getInstance().imageFileLoader = HJImageFileLoader(activity)`

**Comment by design365** [comment]
not your bug ,it's the image picker's bug.  Image constructor not allow that the name is null.
