### ISSUE TITLE
Crash in Android 9(Failed to retrieve rebase())

### ISSUE THREAD

**Issue by kynamar** [esafirm/android-image-picker#317]
## Actual Behavior
Crash in Android 9

2020-12-07 09:23:28.384 17979-17979/? I/ResourcesCompat: Failed to retrieve rebase() method
    java.lang.NoSuchMethodException: rebase []
        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getDeclaredMethod(Class.java:2047)
        at androidx.core.content.res.ResourcesCompat$ThemeCompat$ImplApi23.rebase(ResourcesCompat.java:501)
        at androidx.core.content.res.ResourcesCompat$ThemeCompat.rebase(ResourcesCompat.java:477)
        at androidx.appcompat.app.AppCompatDelegateImpl.attachBaseContext2(AppCompatDelegateImpl.java:465)
        at androidx.appcompat.app.AppCompatActivity.attachBaseContext(AppCompatActivity.java:107)
        at com.esafirm.imagepicker.features.ImagePickerActivity.attachBaseContext(ImagePickerActivity.java:37)
        at android.app.Activity.attach(Activity.java:7364)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3386)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

## Specifications

  - Image Picker Version: 2.4.1
  - Android OS: Android 9
  - Phone: Huawei P10

**Comment by esafirm** [comment]
Is this happening on `3.0.0-beta1` ?
This is more like androidx exception rather than image picker
https://androidx.de/androidx/core/content/res/ResourcesCompat.html

**Comment by esafirm** [comment]
Not reproduced

**Comment by maluchi0** [comment]
this issue is occurred Huawei phone. I also reproduced on os9.
