### ISSUE TITLE
[CRASH] - ImagePickerLauncher with CameraOnlyConfig() on sytem back pressed

### ISSUE THREAD

**Issue by GiacomoPis** [esafirm/android-image-picker#359]
In a Fragment, register image picker

    override fun onAttach(context: Context) {
        super.onAttach(context)

        imagePickerLauncher = registerImagePicker { imageList ->
            ....
        }
    }

then launch

`imagePickerLauncher.launch(
                    CameraOnlyConfig()
                )`

## Scenario
Launch image picker launcher with CameraOnlyConfig() config, camera appears. Instead of shooting photo, press system back.

## Expected Behavior
The camera closes and returns to the previous app screen

## Actual Behavior
The camera closes but a blank screen appears. Press system back another time and the app crashes with the following stack trace.

kotlin.UninitializedPropertyAccessException: lateinit property imagePickerFragment has not been initialized
        at com.esafirm.imagepicker.features.ImagePickerActivity.onBackPressed(ImagePickerActivity.kt:120)
        at android.app.Activity.onKeyUp(Activity.java:3686)
        at android.view.KeyEvent.dispatch(KeyEvent.java:3578)
        at android.app.Activity.dispatchKeyEvent(Activity.java:4003)
        at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:569)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3054)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:624)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6489)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6353)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5793)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5846)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5812)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5968)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5820)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6025)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5793)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5846)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5812)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5820)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5793)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5846)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5812)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6001)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6170)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3826)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:3308)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:3299)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3803)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:197)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

## Specifications

  - Image Picker Version: 3.0.0-beta1
  - Android OS: Android 10
  - Phone: Samsung S9

**Comment by rrsaikat** [comment]
Same error happens for me also! 
Please dev respond ASAP!

nb: Recommended to use fragment lazy initialization rather than initialized into lateinit var. And please don't use force wrap anywhere!

**Comment by esafirm** [comment]
This should be fixed in https://github.com/esafirm/android-image-picker/issues/359
For other suggestions, you can create a PR for it @rrsaikat
