### ISSUE TITLE
Cannot bind argument at index 1 because the index is out of range.  The statement has 0 parameters.

### ISSUE THREAD

**Issue by hoangvuanh761993** [esafirm/android-image-picker#374]
I download the project and it's working fine. But when I try to implement it, it error and I really don't know why, what am I missing? This is my code:

 ```
private val images = arrayListOf<Image>()

    private val imagePickerLauncher = registerImagePicker {
        images.clear()
        images.addAll(it)

        logger("images: $images")
    }

imagePickerLauncher.launch()
```
This is the error: _**java.lang.IllegalArgumentException: Cannot bind argument at index 1 because the index is out of range.  The statement has 0 parameters.**_

```
2021-07-19 10:22:37.741 26094-26212/com.circle.us E/AndroidRuntime: FATAL EXCEPTION: pool-19-thread-1
    Process: com.circle.us, PID: 26094
    java.lang.IllegalArgumentException: Cannot bind argument at index 1 because the index is out of range.  The statement has 0 parameters.
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
        at android.content.ContentResolver.query(ContentResolver.java:1183)
        at com.esafirm.imagepicker.features.fileloader.DefaultImageFileLoader$ImageLoadRunnable.queryData(DefaultImageFileLoader.kt:118)
        at com.esafirm.imagepicker.features.fileloader.DefaultImageFileLoader$ImageLoadRunnable.queryData$default(DefaultImageFileLoader.kt:83)
        at com.esafirm.imagepicker.features.fileloader.DefaultImageFileLoader$ImageLoadRunnable.run(DefaultImageFileLoader.kt:206)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by esafirm** [comment]
@hoangvuanh761993 if you can attach the full stack trace that would be helpful

**Comment by hoangvuanh761993** [comment]
> @hoangvuanh761993 if you can attach the full stack trace that would be helpful

I update my question

**Comment by ablyeom** [comment]
same issue.

**Comment by esafirm** [comment]
Closing this one, moving to https://github.com/esafirm/android-image-picker/issues/381
