### ISSUE TITLE
Crash : Can't create sort clause without columns

### ISSUE THREAD

**Issue by pingothedoer** [esafirm/android-image-picker#378]
## Expected Behavior
ImagePicker should have open the gallery

## Actual Behavior
App crashed with the following exception

`java.lang.IllegalArgumentException: Can't create sort clause without columns.
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:946)
        at com.esafirm.imagepicker.features.fileloader.DefaultImageFileLoader$ImageLoadRunnable.queryData(DefaultImageFileLoader.kt:118)
        at com.esafirm.imagepicker.features.fileloader.DefaultImageFileLoader$ImageLoadRunnable.queryData$default(DefaultImageFileLoader.kt:83)
        at com.esafirm.imagepicker.features.fileloader.DefaultImageFileLoader$ImageLoadRunnable.run(DefaultImageFileLoader.kt:206)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)`

## Steps to Reproduce the Problem

  1.  Launch  ` photoLauncher.launch(ImagePickerConfig())`
  2. App crashes

Saw the same issue, but it was closed. I don't know whether the update has been published or not.

## Specifications

  - Image Picker Version: 3.0.0-beta4
  - Android OS: 10
  - Phone: Nokia 7.2

**Comment by DuoBlood** [comment]
I have the same crash.

Android 10
Pixel 3
lib version: 3.0.0-beta4

**Comment by cikichen** [comment]
+1，me too

**Comment by Fredrick422** [comment]
I am still experiencing this.

**Comment by felipecs81** [comment]
The issue still exists.
Library version: 3.0.0-beta4
Android version 10.0

**Comment by esafirm** [comment]
Can you check if the issue is still there in `3.0.0`

**Comment by ronenfe** [comment]
That's where it happens. I have the same problem in my app:

```
            if (useNewApi) {
                val args = Bundle().apply {
                    // Sort function
                    putStringArray(
                        ContentResolver.QUERY_ARG_SORT_COLUMNS,
                        arrayOf(MediaStore.Files.FileColumns.DATE_MODIFIED)
                    )
                    putInt(
                        ContentResolver.QUERY_ARG_SORT_DIRECTION,
                        ContentResolver.QUERY_SORT_DIRECTION_DESCENDING
                    )
                    // Selection
                    putString(
                        ContentResolver.QUERY_ARG_SQL_SELECTION,
                        selection
                    )
                    // Limit
                    if (limit != null) {
                        putInt(ContentResolver.QUERY_ARG_LIMIT, limit)
                    }
                }

                return context.contentResolver.query(sourceUri, projection, args, null)
            }
```
