### ISSUE TITLE
Cannot bind argument at index 1 because the index is out of range.  The statement has 0 parameters.

### ISSUE THREAD

**Issue by nisrinalya** [esafirm/android-image-picker#381]
Hello! First of all, thank you for making this library. But just now I got this problem when I tried to implement your library:
```
2021-08-16 16:38:33.262 25135-25207/com.bakoelasa.bakoelasakotlintest E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
    Process: com.bakoelasa.bakoelasakotlintest, PID: 25135
    java.lang.IllegalArgumentException: Cannot bind argument at index 1 because the index is out of range.  The statement has 0 parameters.
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
        at android.content.ContentResolver.query(ContentResolver.java:1183)
        at com.esafirm.imagepicker.features.fileloader.DefaultImageFileLoader$ImageLoadRunnable.queryData(DefaultImageFileLoader.kt:118)
        at com.esafirm.imagepicker.features.fileloader.DefaultImageFileLoader$ImageLoadRunnable.queryData$default(DefaultImageFileLoader.kt:83)
        at com.esafirm.imagepicker.features.fileloader.DefaultImageFileLoader$ImageLoadRunnable.run(DefaultImageFileLoader.kt:206)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

The sample from library is doing fine when I try to build it, but I found this problem when I try to implement the library into my project. I don't know what to do to solve this problem because it seems like the error is from the library. I would be very happy if anyone can help me to solve this. Thank you in advance.

**Comment by myc185** [comment]
> I have the same issue when target android 11 sdk 30

me, too

**Comment by myc185** [comment]
I have solve this issue by import **imagepicker** module to my project using source code

**Comment by nikhilvachhani** [comment]
@myc185, can you please provide the edited source code?

**Comment by esafirm** [comment]
<img width="397" alt="Screen Shot 2022-04-24 at 12 02 10" src="https://user-images.githubusercontent.com/1691440/164957418-70e1dc0a-53ce-43d7-91e7-c0b50ce0bd37.png">

Just realized I had some fixes for Android Q and it's not released yet. Can you folks try `3.0.0-beta5`?
Thank you

**Comment by esafirm** [comment]
Closing due inactivity.
