### ISSUE TITLE
Caused by android.content.res.Resources$NotFoundException - com.esafirm.imagepicker.helper.ViewUtils.getArrowIcon (ViewUtils.java:19)

### ISSUE THREAD

**Issue by jerinamathews** [esafirm/android-image-picker#435]
## Actual Behavior
Seeing this crash in crashlytics
stack trace

> Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxxx.xxx/com.esafirm.imagepicker.features.ImagePickerActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f08009d
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3771)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3929)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:257)
       at android.app.ActivityThread.main(ActivityThread.java:8246)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

> Caused by android.content.res.Resources$NotFoundException: Resource ID #0x7f08009d
       at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:304)
       at android.content.res.Resources.getDrawableForDensity(Resources.java:1070)
       at android.content.res.Resources.getDrawable(Resources.java:1010)
       at android.content.Context.getDrawable(Context.java:693)
       at androidx.core.content.ContextCompat$Api21Impl.getDrawable(ContextCompat.java:1012)
       at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:522)
       at com.esafirm.imagepicker.helper.ViewUtils.getArrowIcon(ViewUtils.java:19)
       at com.esafirm.imagepicker.features.ImagePickerActivity.setupView(ImagePickerActivity.kt:153)
       at com.esafirm.imagepicker.features.ImagePickerActivity.onCreate(ImagePickerActivity.kt:78)
       at android.app.Activity.performCreate(Activity.java:8119)
       at android.app.Activity.performCreate(Activity.java:8103)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1359)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3744)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3929)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:257)
       at android.app.ActivityThread.main(ActivityThread.java:8246)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

## Specifications

  - Image Picker Version: 3.0.0
  - Android OS: Seen in multiple android versions 8,11 and 12
  - Phone: seen in multiple devices

**Comment by paulinar** [comment]
+1 Seeing this crash in Sentry too for my production build. 

**Specifications**
Image Picker Version: 3.0.0
Android OS: version 8
Phone: Nexus 5
