### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by shuvo6904** [esafirm/android-image-picker#436]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bd.example.app/com.esafirm.imagepicker.features.ImagePickerActivity}: java.lang.ClassCastException: ne.a cannot be cast to pe.a
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3628)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3873)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2197)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:268)
       at android.app.ActivityThread.main(ActivityThread.java:8016)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)

  - Image Picker Version: 2.3.2

**Comment by stempediaDhruv** [comment]
If getting crash in production/ release when Obfuscation is on add this:

```
 -keepclassmembers class com.esafirm.** {
       *;
     }
```
