### ISSUE TITLE
java.lang.IllegalArgumentException: Abusive '1000' conflicts with requested '1000'

### ISSUE THREAD

**Issue by khemrajsharma** [esafirm/android-image-picker#441]
## Expected Behavior
It should not crash

## Actual Behavior
Crashing when requesting for image

## Steps to Reproduce the Problem

```
java.lang.IllegalArgumentException: Abusive '1000' conflicts with requested '1000'
                                                                                                    	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
                                                                                                    	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
                                                                                                    	at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
                                                                                                    	at android.content.ContentResolver.query(ContentResolver.java:1256)
                                                                                                    	at com.esafirm.imagepicker.features.fileloader.DefaultImageFileLoader$ImageLoadRunnable.queryData(DefaultImageFileLoader.kt:127)
                                                                                                    	at com.esafirm.imagepicker.features.fileloader.DefaultImageFileLoader$ImageLoadRunnable.run(DefaultImageFileLoader.kt:209)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:922)
```
## Specifications

  - Image Picker Version: 3.0.0
  - Android OS: 12
  - Phone: vivo 1920

**Comment by Makwana619** [comment]
any fixes?

**Comment by chebum** [comment]
That's not a problem on the image picker. Exception is raised by `com.vlite.sdk.servicehook.a.f ` which seems to be some third-party gallery app that causes the problem.
