### ISSUE TITLE
Data is always null on Samsung s4

### ISSUE THREAD

**Issue by sandeshlasnapure** [esafirm/android-image-picker#52]
Data is always null in onActivityResult on samsung galaxy s4 android v 5.0.1

**Comment by sandeshlasnapure** [comment]
I am using camera only code.

**Comment by sandeshlasnapure** [comment]
In demo application second time image capture causes crash

**Comment by esafirm** [comment]
Do you mean `Intent` in `onActivityResult`? 

> In demo application second time image capture causes crash
I can't reproduce this, can you send me some stack trace. 

And please use `DefaultCameraModule` as `ImmediateCameraModule` is not really reliable.

**Comment by sandeshlasnapure** [comment]
` Process: com.esafirm.imagepicker.sample, PID: 10157
                                                                                java.lang.RuntimeException: Unable to resume activity {com.esafirm.imagepicker.sample/com.esafirm.sample.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=3000, result=-1, data=null} to activity {com.esafirm.imagepicker.sample/com.esafirm.sample.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
                                                                                    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3403)
                                                                                    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3434)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2772)
                                                                                    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4471)
                                                                                    at android.app.ActivityThread.access$1000(ActivityThread.java:177)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1455)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:145)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5951)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
                                                                                 Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=3000, result=-1, data=null} to activity {com.esafirm.imagepicker.sample/com.esafirm.sample.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
                                                                                    at android.app.ActivityThread.deliverResults(ActivityThread.java:4067)
                                                                                    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3389)
                                                                                    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3434) 
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2772) 
                                                                                    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4471) 
                                                                                    at android.app.ActivityThread.access$1000(ActivityThread.java:177) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1455) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:145) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5951) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183) 
                                                                                 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
                                                                                    at com.esafirm.imagepicker.helper.ImagePickerUtils.getNameFromFilePath(ImagePickerUtils.java:50)
                                                                                    at com.esafirm.imagepicker.model.ImageFactory.singleListFromPath(ImageFactory.java:12)
                                                                                    at com.esafirm.imagepicker.features.camera.ImmediateCameraModule.getImage(ImmediateCameraModule.java:18)
                                                                                    at com.esafirm.sample.MainActivity.onActivityResult(MainActivity.java:154)
                                                                                    at android.app.Activity.dispatchActivityResult(Activity.java:6549)
                                                                                    at android.app.ActivityThread.deliverResults(ActivityThread.java:4063)
                                                                                    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3389) 
                                                                                    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3434) 
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2772) 
                                                                                    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4471) 
                                                                                    at android.app.ActivityThread.access$1000(ActivityThread.java:177) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1455) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:145) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5951) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183) 
`

**Comment by sandeshlasnapure** [comment]
Tried using default camera module but no luck.

**Comment by esafirm** [comment]
@sandeshlasnapure did you get the same error with `DefaultCameraModule`?

**Comment by sandeshlasnapure** [comment]
yes

**Comment by iNoles** [comment]
Looks like currentImagePath is null in https://github.com/esafirm/android-image-picker/blob/master/imagepicker/src/main/java/com/esafirm/imagepicker/features/camera/ImmediateCameraModule.java

**Comment by esafirm** [comment]
@iNoles `ImmediateCameraModule` is intended that way. You should use `DefaultCameraModule`

**Comment by esafirm** [comment]
Closing this for now because inactivity. Please feel free to open it again.

**Comment by saran2somu** [comment]
Data is always null on HTC Desire 826.. I am using DefaultCameraModule , but data always return null
Os - Android 6.0.1

**Comment by esafirm** [comment]
@saran2somu please use the latest version and the new API

```
ImagePicker.cameraOnly().start(activity)
```
Thanks!

**Comment by saran2somu** [comment]
Okay @esafirm . Thanks a lot .. :+1:
