### ISSUE TITLE
Retrolambda "NoSuchMethod"

### ISSUE THREAD

**Issue by neofly** [esafirm/android-image-picker#66]
There are a problem with the plugin gradle-retrolambda. It do not compile correctly the lambda. The result is "NoSuchMethod" Exception with the last binary. I try to compile myself, it do not change the result, even if I update retrolambda to 3.7.0. In Android Studio 2.3, jack is available but do not work with library. Only solution seems to be Android Studio 3.0, but it is in preview.

I would be good to recompile the project, because now the library is unusable.

**Comment by esafirm** [comment]
Can you share the full stacktrace?

**Comment by neofly** [comment]
The config in gradle

```
compile 'com.github.bumptech.glide:glide:3.7.0'
compile 'com.github.esafirm.android-image-picker:imagepicker:1.7.4@aar'
```

The intent I create and send with a intent chooser in the extra Intent.EXTRA_INITIAL_INTENTS.

```
ImagePicker customGallery = ImagePicker.create(getActivity())
    .returnAfterFirst(false) // set whether pick or camera action should return immediate result or not. For pick image only work on single mode
    .folderMode(false) // folder mode (false by default)
    .imageTitle("Tap to select") // image selection title
//    .limit(10) // max images can be selected (99 by default)
    .showCamera(true) // show camera or not (true by default)
//    .imageDirectory("Camera") // directory name for captured image  ("Camera" folder by default)
    .enableLog(false); // disabling log

if (multiple) {
    customGallery.single(); // single mode
} else {
    customGallery.multi(); // multi mode (default mode)
}

Intent customGalleryIntent = customGallery.getIntent(getActivity());
customGalleryIntent.putExtra(IntentUtils.EXTRA_CHOOSER_RESOLVE, false);
intents.add(customGalleryIntent);
```

The full stacktrace.

```
07-27 15:29:15.884 12639-12639/com.neofly.*** E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.neofly.***, PID: 12639
                                                                            java.lang.NoSuchMethodError: No static method com_esafirm_imagepicker_features_ImagePickerPresenter$1$$Lambda$1_lambda$onImageLoaded$11(Lcom/esafirm/imagepicker/features/ImagePickerPresenter$1;Ljava/util/List;Ljava/util/List;)V in class Lcom/esafirm/imagepicker/features/ImagePickerPresenter$1; or its super classes (declaration of 'com.esafirm.imagepicker.features.ImagePickerPresenter$1' appears in /data/app/com.neofly.***/base.apk)
                                                                                at com.esafirm.imagepicker.features.ImagePickerPresenter$1$$Lambda$1.run(Unknown Source)
                                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:158)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by esafirm** [comment]
@neofly it seems that i can't reproduce this. I think this is related to Multidex behaviour. Did you use Multidex? If you use it, did you already configure it well?

**Comment by neofly** [comment]
I didn't use Multidex. I try with Multidex but I have the same result. 

I use jack in my project for lambda. Maybe it's the problem.

**Comment by hassaanjamil** [comment]
Please find you didn't added a dependency which is conflicting with it. In my case [PhotoPickView](https://github.com/Werb/PickPhotoSample) library's dependency and configuration's causes the dex problem, by removing its configuration, code snippet was working fine.

**Comment by esafirm** [comment]
@neofly That could be it. Any update on this? I didn't have time to test it with jack. Now jack is officially deprecated, maybe you should move to AS 3.0 desugar or retrolambda 😄

**Comment by esafirm** [comment]
Will closing this due inactivity. Please reopen if the problem still occurs or anyone have a solution.
