### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by Rainer-Lang** [esafirm/android-image-picker#75]
```java
java.lang.ClassCastException: MY_PACKAGE.GlideRequests cannot be cast to com.esafirm.imagepicker.features.imageloader.GlideRequests
at com.esafirm.imagepicker.features.imageloader.GlideApp.with(GlideApp.java:73)
at com.esafirm.imagepicker.features.imageloader.DefaultImageLoader.loadImage(DefaultImageLoader.java:12)
at com.esafirm.imagepicker.adapter.FolderPickerAdapter.onBindViewHolder(FolderPickerAdapter.java:40)
at com.esafirm.imagepicker.adapter.FolderPickerAdapter.onBindViewHolder(FolderPickerAdapter.java:19)
at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6482)
```

**Comment by Rainer-Lang** [comment]
Maybe this is related: https://github.com/bumptech/glide/issues/2393

**Comment by esafirm** [comment]
@Rainer-Lang will check on it. Hacktoberfest materila? 😄

**Comment by bvklimov** [comment]
Hi! Facing with the same issue, cannot register http client in GlideModule for my purposes, because of image-picker extends AppGlideModule, and not LibraryGlideModule, I think.

**Comment by esafirm** [comment]
@bvklimov so i think changing the library glide module name will solve the issue right? Will look into it in the weekend!

**Comment by cheetahdeliverys** [comment]
I have the same problem, I think it is because of new version of glide added to my project, some of its methods and syntax to use them become different, please solve it thanks a lot

**Comment by esafirm** [comment]
Can you please try this version -> https://github.com/esafirm/android-image-picker/releases/tag/1.10.0-beta1

BTW you should consider using `implementation` rather than `compile` if you still using Glide v3 in your project

**Comment by esafirm** [comment]
Closing this issue due inactivity. Please don't hesitate to re-open
