### ISSUE TITLE
LinearLayout$LayoutParams cannot be cast to

### ISSUE THREAD

**Issue by tristangrichard** [esafirm/android-image-picker#80]
Hi great library!!
I'm getting a weird crash with the new version 1.9.0 on an HTC Defy 4.4.3

```
Fatal Exception: java.lang.ClassCastException: android.widget.LinearLayout$LayoutParams cannot be cast to com.android.internal.widget.ActionBarOverlayLayout$LayoutParams
       at com.android.internal.widget.ActionBarOverlayLayout.applyInsets(ActionBarOverlayLayout.java:172)
       at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:317)
       at android.view.View.measure(View.java:16654)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5150)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2421)
       at android.view.View.measure(View.java:16654)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2064)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1189)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1374)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1076)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5913)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:807)
       at android.view.Choreographer.doCallbacks(Choreographer.java:601)
       at android.view.Choreographer.doFrame(Choreographer.java:562)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:791)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:157)
       at android.app.ActivityThread.main(ActivityThread.java:5867)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Any idea what is causing this. I am unable to reproduce it my self!

**Comment by shimiuh** [comment]
I am getting the same crash are you sure it is from android-image-picker?

**Comment by esafirm** [comment]
@trr-amsiq @shimiuh Hi! and thank you. 
Yeah i'm not sure if this crash is from the library. Unless you have a way to reproduce it, i think i will ignoring this for now.

BTW, have you looked at this [SO](https://stackoverflow.com/questions/30004814/classcastexception-android-widget-linearlayoutlayoutparams-cannot-be-cast-to-c)

**Comment by trr-amsiq** [comment]
@shimiuh Yes I am sure. I am logging the users navigation.

@esafirm I don't have any of the devices that are crashing. I've already tried the link you are linking to without luck

**Comment by appspell** [comment]
do you have any update there? we are experiencing the same issue now :)
