### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by hadalaba** [esafirm/android-image-picker#92]
I don't know why, but sometimes I getting this error:
`
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.example.projecthelper, PID: 7492
                                                                         java.lang.NullPointerException: Attempt to invoke interface method 'void com.esafirm.imagepicker.features.ImagePickerView.showLoading(boolean)' on a null object reference
                                                                             at com.esafirm.imagepicker.features.ImagePickerPresenter.lambda$loadImages$0(ImagePickerPresenter.java:38)
                                                                             at com.esafirm.imagepicker.features.ImagePickerPresenter$$Lambda$1.run(Unknown Source)
                                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

I tried to test it several times, and this happening when you try to select images larger than the specified limit
P.S. ImagePicker version: 1.9.2

**Comment by esafirm** [comment]
Fixed in here https://github.com/esafirm/android-image-picker/commit/d7f8e4562271017e5fb9402a93a2b6407eaf60c7
