### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by hadalaba** [esafirm/android-image-picker#95]
>  E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         java.lang.NullPointerException
                                                                             at com.esafirm.imagepicker.features.ImagePickerPresenter.lambda$loadImages$0(ImagePickerPresenter.java:38)
                                                                             at com.esafirm.imagepicker.features.ImagePickerPresenter$$Lambda$1.run(Unknown Source)
                                                                             at android.os.Handler.handleCallback(Handler.java:615)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                             at android.os.Looper.loop(Looper.java:137)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:4921)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:511)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
                                                                             at dalvik.system.NativeStart.main(Native Method)

The error appeared while debugging on a Samsung GS2 device

**Comment by esafirm** [comment]
This is the as as https://github.com/esafirm/android-image-picker/issues/92 

Released in 1.9.3 
https://github.com/esafirm/android-image-picker/releases/tag/1.9.3
