### ISSUE TITLE
Activity destruction leads to a delayed camera photo creation

### ISSUE THREAD

**Issue by absimas** [esafirm/android-image-picker#96]
Basically when image picker activity is destroyed while we're taking a photo, the picker fails to fetch the newly taken photo.

When in a multi-selection mode, after taking a picture, it appears in the picker after around 5 seconds. This delay is probably why `returnAfterFirst` returns a null list.

All is fine when picker activity is not destroyed.

---

Recreate:
1. Enable "Do not keep activities" in android developer settings.
2. Start picker with the following settings
```
	.returnAfterFirst(true)
	.single()
	.showCamera(true)
```
3. Take a camera picture and accept
4. `onActivityResult` yields no images.

**Comment by esafirm** [comment]
@absimas will check on it.

**Comment by matheusjardimb** [comment]
I'm pretty sure I'm facing the same issue

**Comment by esafirm** [comment]
@absimas @matheusjardimb fixed in here 
https://github.com/esafirm/android-image-picker/commit/d25bb8d8edf6526d6fa64e3dd622708c9510c031

Please check the release -> https://github.com/esafirm/android-image-picker/releases/tag/1.9.4

**Comment by absimas** [comment]
```java
java.lang.IllegalStateException: Camera Module must be set first
  at com.esafirm.imagepicker.features.ImagePickerPresenter.captureImage(ImagePickerPresenter.java:91)
  at com.esafirm.imagepicker.features.ImagePickerActivity.captureImage(ImagePickerActivity.java:378)
  at com.esafirm.imagepicker.features.ImagePickerActivity.captureImageWithPermission(ImagePickerActivity.java:360)
  at com.esafirm.imagepicker.features.ImagePickerActivity.onOptionsItemSelected(ImagePickerActivity.java:214)
  at android.app.Activity.onMenuItemSelected(Activity.java:3383)
  at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:380)
  at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
  at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
  at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
  at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:63)
  at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:203)
  at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
  at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
  at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
  at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
  at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963)
  at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
  at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150)
  at android.view.View.performClick(View.java:6261)
  at android.widget.TextView.performClick(TextView.java:11159)
  at android.view.View$PerformClick.run(View.java:23748)
  at android.os.Handler.handleCallback(Handler.java:751)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6776)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

`ImagePickerPresenter.java` says module is late initialized, but it isn't. Except when restoring state in which case it will just be null:
```java
/* Camera Module is late initiated */
void setCameraModule(DefaultCameraModule cameraModule) {
    this.cameraModule = cameraModule;
}
```

**Comment by esafirm** [comment]
@absimas w00t. Last minute change fuck it up. Will push the fix ASAP

**Comment by absimas** [comment]
No problem :)

**Comment by esafirm** [comment]
@absimas here it is https://github.com/esafirm/android-image-picker/releases/tag/1.9.5 🎉

**Comment by absimas** [comment]
@esafirm works perfectly. Thanks :+1:
